/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  
      // type: 'html',
      // value: '<img src="docusaurus.png" alt="Sponsor" />', // 要渲染的 HTML
      // defaultStyle: true, // 使用默认的菜单项目样式

  JavaScript: [
    {
      type: 'html',
      value: 'JavaScript',
      className: 'sidebar-title',
    },
    doc("JavaScript/JS语句", "JS语句"),
    doc("JavaScript/JS数组", "JS数组"),
    doc("JavaScript/JS异步", "JS异步"),
    doc("JavaScript/JS模块", "JS模块"),
    doc("JavaScript/JS类型、值和变量", "JS类型、值和变量"),
    doc("JavaScript/JS类", "JS类"),
    // doc("JavaScript/JS函数", "JS函数"),
    // category("JavaScript/JS函数", "JS函数", [
    //   doc("JavaScript/JS函数/函数定义", "函数定义"),
    //   doc("JavaScript/JS函数/函数调用", "函数调用"),
    //   doc("JavaScript/JS函数/形参与实参", "形参与实参"),
    // ]),
    category("JavaScript/JS函数", "JS函数", [
      doc("JavaScript/JS函数/函数定义", "函数定义"),
      doc("JavaScript/JS函数/函数调用", "函数调用"),
      doc("JavaScript/JS函数/形参与实参", "形参与实参"),
    ]),
    doc("JavaScript/JS对象", "JS对象"),
    doc("JavaScript/JS迭代器与生成器", "JS迭代器与生成器"),
    doc("JavaScript/JS表达式与操作符", "JS表达式与操作符"),
  ],

  network:[
    doc("Network/计算机网络/应用层", "应用层"),
  ]
};


function doc(id, label) {
  return {
    type: "doc",
    id: id,
    label: label,
  };
}

function category(id, label, items) {
  return {
    type: "category",
    label: label,
    collapsible: true,
    collapsed: true,
    link: {
      // type: "doc",
      id: id,
    },
    items: items,
  };
}
module.exports = sidebars;
